# https://neo4j.com/docs/operations-manual/current/docker/docker-compose-standalone/
FROM neo4j:2025.02.0

RUN echo "Creating working dir and copying files"
RUN mkdir /app
WORKDIR /app
COPY . .

RUN neo4j-admin dbms set-initial-password examplepw

CMD ["bash", "run.sh"]