services:
  neo4j: # https://neo4j.com/docs/operations-manual/current/docker/docker-compose-standalone/
    build:
      context: ./neo4j
      dockerfile: dockerfile
    ports:
      - '7687:7687'
      - '7474:7474'
    networks:
      - testnet
    restart: unless-stopped
    #volumes:
    #  - /$HOME/neo4j/logs:/logs
    #  - /$HOME/neo4j/config:/config
    #  - /$HOME/neo4j/data:/data
    #  - /$HOME/neo4j/plugins:/plugins
    #environment:
    #  - NEO4J_AUTH=neo4j/examplepw

  bootgraph:
    build:
      context: ./bootgraph
      dockerfile: dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - neo4j
    networks:
      - testnet
    restart: unless-stopped

networks:
  testnet:
    driver: bridge